### ISSUE TITLE
无法读取软件列表

### ISSUE THREAD

**Issue by hsyyhcc** [DustinWin/softmanager#1]
不管是以前使用文件替换libararies，还是如今学着用批处理去更新，都存在无法读取软件列表的问题，表现为点击“升级”一栏后，直接空白。并且在软件库中点开相应的电脑上已经安装的软件，也提示需要安装。我在三四台电脑上同时使用作者的软件更新，有三台是这么个情况，只有一台能正常更新。有时候更新软件库文件后能解决，很多时候并不能。但诡异的是，卸载界面能看到软件列表。
![软件列表空白](https://github.com/user-attachments/assets/a4635601-b5fb-470b-97eb-76d32affbe99)

**Comment by DustinWin** [comment]
我刚刚试了，没遇到你所说的问题，你是下载的哪个完整包？

**Comment by DustinWin** [comment]
我在 Windows 沙盒内按照正常流程安装和打开，发现软件库停留在 2023-8-19，可以确定这是腾讯方面的 bug。
![QQ20241019-181414](https://github.com/user-attachments/assets/2da961ad-0c33-4839-9a32-355c024ba097)

**Comment by hsyyhcc** [comment]
> 找到问题原因了，通过 Actions 获取到的 SoftVerInfo.etf 文件是不完整的，我再看看有没有解决方法。

感谢跟进，辛苦啦。

**Comment by DustinWin** [comment]
腾讯已经修复了这个 bug，你再下载了试试。

**Comment by hsyyhcc** [comment]
应该是没有问题了，我找到一台前阵子不能更新的电脑，重新打开了一下，能刷出升级列表了。感谢跟进。

**Comment by DustinWin** [comment]
> 应该是没有问题了，我找到一台前阵子不能更新的电脑，重新打开了一下，能刷出升级列表了。感谢跟进。

好的。

**Comment by hsyyhcc** [comment]
嗯，不知道还该不该打扰。其实，这问题依然没有得到解决，目前我所有电脑都用不了了，刷不出来软件列表。

**Comment by DustinWin** [comment]
> 嗯，不知道还该不该打扰。其实，这问题依然没有得到解决，目前我所有电脑都用不了了，刷不出来软件列表。

似乎是腾讯那边又抽风了~
